apiVersion: v1
kind: Service
metadata:
  name: auth-api-service
  namespace: local
  annotations:
    batata.me/owner: jersonsatoru@yahoo.com.br
spec:
  selector:
    app: auth-api-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
