apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api-deployment
  labels:
    app: user-api-deployment
  namespace: local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-api-deployment
  template:
    metadata:
      labels:
        app: user-api-deployment
    spec:
      containers:
      - name: user-api-app
        image: localhost:5001/user-api
        ports:
        - containerPort: 4000
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "128m"
            memory: "256Mi"
          limits:
            cpu: "256m"
            memory: "512Mi"
        livenessProbe:
          initialDelaySeconds: 3
          failureThreshold: 2
          periodSeconds: 3
          httpGet:
            path: "/v1/healthz"
            port: 4000
        readinessProbe:
          initialDelaySeconds: 3
          failureThreshold: 2
          periodSeconds: 3
          httpGet:
            path: "/v1/healthz"
            port: 4000
