apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: local-ingress
  namespace: local
  annotations:
    batata.me/owner: jersonsatoru@yahoo.com.br
    konghq.com/strip-path: "true"
spec:
  ingressClassName: "kong"
  rules:
  - host: batata.me
    http:
      paths:
      - path: /api/user
        pathType: Prefix
        backend:
          service:
            name: user-api-service
            port:
              number: 80
  - host: batata.me
    http:
      paths:
      - path: /api/auth
        pathType: Prefix
        backend:
          service:
            name: auth-api-service
            port:
              number: 80
