apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api-deployment
  namespace: local
  labels:
    app: auth-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-api-deployment
  template:
    metadata:
      labels:
        app: auth-api-deployment
    spec:
      containers:
      - name: auth-api-app
        image: localhost:5001/auth-api
        ports:
        - containerPort: 4000
        imagePullPolicy: Always
        resources:
          requests:
            memory: '256Mi'
            cpu: '128m'
          limits:
            memory: '512Mi'
            cpu: '256m'
        livenessProbe:
          initialDelaySeconds: 3
          failureThreshold: 2
          periodSeconds: 3
          httpGet:
            path: '/v1/healthz'
            port: 4000
        readinessProbe:
          initialDelaySeconds: 3
          failureThreshold: 2
          periodSeconds: 3
          httpGet:
            path: '/v1/healthz'
            port: 4000
